language: python

python:
  - "3.6"

env:
  - DEPS="Django>=1.11,<1.12"
  - DEPS="Django>=2.0,<2.1"
  - DEPS="Django>=2.1,<2.2"
  - NODE="validate"

install:
  - if [ $DEPS ]; then pip install pipenv codecov; fi
  - if [ $DEPS ]; then pipenv install --dev; fi
  - if [ $DEPS ]; then pipenv run pip install -e .; fi
  - if [ $DEPS ]; then pipenv run pip install $DEPS; fi
  - if [ $NODE ]; then pip install nodeenv && nodeenv --node=11.3.0 env; fi

script:
  - if [ $DEPS ]; then pipenv run py.test --cov; fi
  - if [ $NODE ]; then . ./env/bin/activate && npm run $NODE; fi

after_success:
  - codecov
